<a href="https://colab.research.google.com/github/GeraldineQuispeT/Programacion101_UTEC/blob/main/PC_3_Geraldine_Quispe_Tapara.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Pregunta 1

a) Crea un array unidimensional que contenga los números primos entre 1 y 50.

In [6]:
array_1d = np.arange(1,51)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [7]:
def es_primo(numero): #se genera la funcion para determinar si el numero es primo o no
  if numero < 2:
    return False
  else:
    for i in range(2, numero):
      if numero % i == 0:
        return False
    return True

In [10]:
array_1d_primos = np.array([numero for numero in array_1d if es_primo(numero)])
array_1d_primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47])

b) Convierte el array unidimensional anterior en una matriz de forma (n, 2), donde n es el número adecuado de
filas. Si es necesario, agrega ceros al final del array para completar la matriz.

In [13]:
array_1d_primos.shape[0]%2 #al ser diferente de cero es necesario agregar un cero para tener un numero igual de filas

1

In [22]:
array_1d_primos_= np.concatenate((array_1d_primos, [0]))
array_1d_primos_ = array_1d_primos_.reshape(int(array_1d_primos_.shape[0]/2), 2)
array_1d_primos_

array([[ 2,  3],
       [ 5,  7],
       [11, 13],
       [17, 19],
       [23, 29],
       [31, 37],
       [41, 43],
       [47,  0]])

In [23]:
array_1d_primos_.shape

(8, 2)

c) Calcula la suma de cada fila y crea un nuevo array que contenga estos valores.


In [24]:
sum_filas = np.sum(array_1d_primos_,axis=1)
sum_filas

array([ 5, 12, 24, 36, 52, 68, 84, 47])

## Pregunta 2

a) Crea un array bidimensional de forma (4, 4) que contenga números enteros aleatorios entre 1 y 100.

In [26]:
array_aleat = np.random.randint(1,100, (4,4))
array_aleat

array([[62, 22, 14, 50],
       [29, 97, 81, 83],
       [29,  2, 83,  6],
       [63, 44, 45, 94]])

b) Cambia el tipo de datos del array a float64 y divide todos los elementos por 3.7.

In [28]:
array_aleat = array_aleat.astype(np.float64)
array_aleat/3.7

array([[16.75675676,  5.94594595,  3.78378378, 13.51351351],
       [ 7.83783784, 26.21621622, 21.89189189, 22.43243243],
       [ 7.83783784,  0.54054054, 22.43243243,  1.62162162],
       [17.02702703, 11.89189189, 12.16216216, 25.40540541]])

c) Calcula y muestra las siguientes propiedades del array resultante:
● Dimensiones (ndim)
● Forma (shape)
● Tamaño total (size)
● Tipo de datos (dtype

In [31]:
print(f'Las dimensiones de la matriz son: {array_aleat.ndim}')
print(f'La forma de la matriz son: {array_aleat.shape}')
print(f'El tamaño total de la matriz son: {array_aleat.size}')
print(f'Los tipos de datos de la matriz son: {array_aleat.dtype}')

Las dimensiones de la matriz son: 2
La forma de la matriz son: (4, 4)
El tamaño total de la matriz son: 16
Los tipos de datos de la matriz son: float64


## Pregunta 3

a) Crea un array x que contenga 100 valores equiespaciados entre -10 y 10.

In [32]:
array_x = np.linspace(-10,10,100)
array_x

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

b) Calcula el valor de la función f(x)=e**(-x**2) para cada elemento de x.

In [34]:
fx = np.exp(array_x**2)
fx

array([2.68811714e+43, 4.92546807e+41, 9.79255047e+39, 2.11248251e+38,
       4.94469400e+36, 1.25584116e+35, 3.46081988e+33, 1.03483778e+32,
       3.35748861e+30, 1.18196826e+29, 4.51487855e+27, 1.87126513e+26,
       8.41537689e+24, 4.10639583e+23, 2.17418775e+22, 1.24905704e+21,
       7.78603749e+19, 5.26622857e+18, 3.86484349e+17, 3.07760666e+16,
       2.65915288e+15, 2.49300124e+14, 2.53600833e+13, 2.79916082e+12,
       3.35238601e+11, 4.35641436e+10, 6.14261558e+09, 9.39780622e+08,
       1.56008632e+08, 2.81008699e+07, 5.49211843e+06, 1.16468643e+06,
       2.67995273e+05, 6.69104951e+04, 1.81263494e+04, 5.32813775e+03,
       1.69937621e+03, 5.88101949e+02, 2.20833368e+02, 8.99758106e+01,
       3.97773487e+01, 1.90807258e+01, 9.93122778e+00, 5.60867129e+00,
       3.43689312e+00, 2.28518339e+00, 1.64863716e+00, 1.29055972e+00,
       1.09617557e+00, 1.01025527e+00, 1.01025527e+00, 1.09617557e+00,
       1.29055972e+00, 1.64863716e+00, 2.28518339e+00, 3.43689312e+00,
      


c) Encuentra el valor máximo y mínimo de f(x) y las posiciones en el array donde ocurren

In [47]:
posiciones_maximo = np.where(fx == fx.max())[0]
posiciones_minimo = np.where(fx == fx.min())[0]

In [48]:
posiciones_maximo

array([ 0, 99])

In [49]:
posiciones_minimo

array([49, 50])

## Pregunta 4


a) Extrae un subarray que contenga los elementos en posiciones pares de filas y columnas (es decir, filas y
columnas con índices 0, 2, 4, 6, 8).

In [57]:
array_1 = np.arange(1, 101).reshape(10, 10)
array_1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [58]:
subarray = array_1[::2, ::2]
print("Subarray:\n", subarray)

Subarray:
 [[ 1  3  5  7  9]
 [21 23 25 27 29]
 [41 43 45 47 49]
 [61 63 65 67 69]
 [81 83 85 87 89]]


b) Reemplaza todos los elementos que son múltiplos de 3 por -1.

In [59]:
subarray[subarray % 3 == 0] = -1
subarray

array([[ 1, -1,  5,  7, -1],
       [-1, 23, 25, -1, 29],
       [41, 43, -1, 47, 49],
       [61, -1, 65, 67, -1],
       [-1, 83, 85, -1, 89]])

c) Utiliza indexación avanzada para extraer todos los números primos del array original y crea un nuevo array
con estos valores.

In [63]:
array_1_primos = np.array([numero for numero in array_1.flat if es_primo(numero)])
array_1_primos

array([ 2,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61,
       67, 71, 73, 79, 83, 89, 97])

## Pregunta 5

a) Crea tres arrays unidimensionales de longitud 5 con números aleatorios entre 0 y 1.

In [67]:
array_1 = np.random.rand(5, )
array_2 = np.random.rand(5, )
array_3 = np.random.rand(5, )

b) Combina estos arrays para formar una matriz de forma (5, 3).

In [77]:
concat_array = np.concatenate(([array_1], [array_2],[array_3])).T
concat_array

array([[0.95995495, 0.52337482, 0.71486524],
       [0.74107718, 0.82172492, 0.97432496],
       [0.06543252, 0.03837838, 0.05429286],
       [0.244815  , 0.57704968, 0.73872083],
       [0.62513981, 0.71683374, 0.55160408]])

In [78]:
concat_array.shape

(5, 3)

c) Agrega una columna de unos al principio de la matriz resultante, obteniendo una matriz de forma (5, 4).

In [79]:
concat_array = np.concatenate(([np.ones(5)],[array_1], [array_2],[array_3])).T
concat_array

array([[1.        , 0.95995495, 0.52337482, 0.71486524],
       [1.        , 0.74107718, 0.82172492, 0.97432496],
       [1.        , 0.06543252, 0.03837838, 0.05429286],
       [1.        , 0.244815  , 0.57704968, 0.73872083],
       [1.        , 0.62513981, 0.71683374, 0.55160408]])

d) Reordena las columnas de la matriz para que la columna de unos esté al final.

In [84]:
concat_array_ = concat_array[:, ::-1]
concat_array_

array([[0.71486524, 0.52337482, 0.95995495, 1.        ],
       [0.97432496, 0.82172492, 0.74107718, 1.        ],
       [0.05429286, 0.03837838, 0.06543252, 1.        ],
       [0.73872083, 0.57704968, 0.244815  , 1.        ],
       [0.55160408, 0.71683374, 0.62513981, 1.        ]])

## Pregunta 6

a) Crea una matriz simétrica positiva definida de tamaño 3x3.

In [85]:
matriz = np.random.rand(3, 3)
matriz_sim = (matriz + matriz.T) / 2
matriz_sim_pos = np.dot(matriz_sim, matriz_sim.T)
matriz_sim_pos


array([[1.00339252, 0.64678149, 0.91188381],
       [0.64678149, 0.68936447, 0.79622979],
       [0.91188381, 0.79622979, 1.33494859]])

b) Calcula sus valores y vectores propios (eigenvalores y eigenvectores).

In [89]:
eigenvalores, eigenvectores = np.linalg.eig(matriz_sim_pos)

In [90]:
eigenvalores

array([2.63639524, 0.24385508, 0.14745527])

In [91]:
eigenvectores

array([[ 0.56485515,  0.80075732,  0.19931478],
       [ 0.46610701, -0.11029452, -0.8778265 ],
       [ 0.68094267, -0.58874684,  0.43553903]])

c) Verifica que la multiplicación de la matriz original por un vector propio es igual al producto del eigenvalor
correspondiente por el vector propio.

In [124]:
# 1 eigenvector y su correspondiente eigenvalor
eigenvalor = eigenvalores[0]
eigenvector = eigenvectores[:, 0]

# Verificar que A * eigenvector = eigenvalor * eigenvector
matriz_x_eigenvector = np.dot(matriz_sim_pos, eigenvector)
eigenvalor_x_eigenvector = eigenvalor * eigenvector

In [129]:
matriz_x_eigenvector

array([1.48918142, 1.22884231, 1.79523401])

In [130]:
eigenvalor_x_eigenvector

array([1.48918142, 1.22884231, 1.79523401])

## Pregunta 7

a) Construye un sistema de ecuaciones lineales con tres ecuaciones y tres incógnitas donde la matriz de
coeficientes es singular (no invertible).

In [97]:
#Matriz de coeficientes
A = np.array([[1, 2, 3],
              [2, 4, 6],
              [3, 6, 9]])

determinante = np.linalg.det(A)

# Comprobar si es singular
if determinante == 0:
    print("La matriz A es singular (no invertible).")
else:
    print("La matriz A es invertible.")

La matriz A es singular (no invertible).


b) Intenta resolver el sistema utilizando np.linalg.solve() y explica el resultado obtenido.

In [100]:
B = np.array([1, 2, 3])

In [101]:
solution = np.linalg.solve(A, B) # No tiene resultado debido a que la matriz es singular
print("Solución del sistema:", solution)

LinAlgError: Singular matrix

## Pregunta 8

a) Crea un array de forma (4, 4, 4) con números enteros aleatorios entre 0 y 100.

In [103]:
array = np.random.randint(0, 101, size=(4, 4, 4))
array

array([[[48, 65, 35, 45],
        [74, 30, 79, 25],
        [ 7, 17, 61, 45],
        [26, 10, 72, 22]],

       [[25, 33, 81, 97],
        [14, 68, 29, 96],
        [92, 91, 70, 44],
        [52, 72,  9, 79]],

       [[64, 17, 47, 19],
        [49,  1, 71, 72],
        [24, 25, 39, 67],
        [60, 57, 29, 65]],

       [[80, 41, 18, 78],
        [37, 26, 16, 27],
        [ 8, 16, 49, 71],
        [47,  6, 91, 80]]])

b) Calcula la suma a lo largo del eje 0, obteniendo un array de forma (4, 4).

In [104]:
suma_eje_0 = np.sum(array, axis=0)
suma_eje_0

array([[217, 156, 181, 239],
       [174, 125, 195, 220],
       [131, 149, 219, 227],
       [185, 145, 201, 246]])

c) Calcula el promedio a lo largo del eje 1, obteniendo un array de forma (4, 4).

In [105]:
promedio_eje_1 = np.mean(array, axis=1)
promedio_eje_1

array([[38.75, 30.5 , 61.75, 34.25],
       [45.75, 66.  , 47.25, 79.  ],
       [49.25, 25.  , 46.5 , 55.75],
       [43.  , 22.25, 43.5 , 64.  ]])

d) Reestructura el array original en una nueva forma de (8, 8) sin perder datos.

In [106]:
array_8_8 = array.reshape(8, 8)
array_8_8

array([[48, 65, 35, 45, 74, 30, 79, 25],
       [ 7, 17, 61, 45, 26, 10, 72, 22],
       [25, 33, 81, 97, 14, 68, 29, 96],
       [92, 91, 70, 44, 52, 72,  9, 79],
       [64, 17, 47, 19, 49,  1, 71, 72],
       [24, 25, 39, 67, 60, 57, 29, 65],
       [80, 41, 18, 78, 37, 26, 16, 27],
       [ 8, 16, 49, 71, 47,  6, 91, 80]])

## Pregunta 9

a) Usando NumPy, crea un array que contenga los primeros 10 elementos de esta secuencia sin utilizar bucles
explícitos.

In [112]:
elementos = np.arange(1,11)
factorial_vectorizado = np.vectorize(np.math.factorial)
factoriales = factorial_vectorizado(elementos)
factoriales

<ipython-input-112-b895f76d6de4>:2: DeprecationWarning: `np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`
  factorial_vectorizado = np.vectorize(np.math.factorial)


array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

b) Calcula la suma de todos los elementos del array creado.

In [114]:
suma_factoriales = np.sum(factoriales)
suma_factoriales

4037913

c) Dado que los factoriales pueden ser números muy grandes, cambia el tipo de datos del array a object para
manejar enteros arbitrariamente grandes y recalcula la suma.

In [115]:
factoriales_object = factoriales.astype(object)
suma_factoriales_object = np.sum(factoriales_object)
suma_factoriales_object

4037913

## Pregunta 10

a) Simula un conjunto de datos que represente las alturas (en cm) de 500 personas, siguiendo una distribución
normal con media 170 y desviación estándar 10.

In [117]:
mean = 170
std_dev = 10
size = 500

# Alturas siguiendo dist normal
alturas = np.random.normal(loc=mean, scale=std_dev, size=size)
alturas

array([182.24661461, 181.01096072, 163.6289556 , 182.23949771,
       153.99209475, 167.30297913, 162.96993009, 170.86956525,
       162.87503119, 162.68282989, 171.86007305, 165.74099806,
       167.86068958, 154.25235362, 186.97972232, 168.0950625 ,
       171.83576079, 168.98677795, 166.59868178, 170.97182588,
       164.90791127, 175.9066011 , 153.22152731, 181.96867867,
       155.62580337, 173.54890795, 157.60191905, 160.88310866,
       167.22888654, 156.62753753, 177.06866624, 169.10092466,
       157.0974546 , 153.22400195, 162.28179622, 172.27956583,
       174.00480099, 173.61164498, 164.58658629, 162.16355196,
       156.81910753, 151.25534821, 192.56815268, 180.5377889 ,
       164.17203201, 158.07748261, 166.36222316, 158.2469675 ,
       170.62488426, 165.13791486, 167.23549752, 181.41260193,
       189.90784156, 168.61655419, 158.45530704, 188.23456294,
       172.19242179, 173.1699129 , 175.41456371, 186.12764939,
       169.35161956, 158.9500258 , 167.89135941, 161.12

c) Encuentra cuántas personas miden más de 180 cm y menos de 160 cm.

In [118]:
mas_de_180 = np.sum(alturas > 180)
mas_de_180

66

In [119]:
menos_de_160 = np.sum(alturas < 160)
menos_de_160

75

d) Normaliza los datos de altura para que tengan media 0 y desviación estándar 1

In [120]:
mean_altura = np.mean(alturas)
std_altura = np.std(alturas)

# Normaliza los datos
alturas_normalizadas = (alturas - mean_altura) / std_altura
alturas_normalizadas

array([ 1.40142099e+00,  1.26725987e+00, -6.19991346e-01,  1.40064828e+00,
       -1.66631352e+00, -2.21084238e-01, -6.91545040e-01,  1.66157853e-01,
       -7.01848688e-01, -7.22716944e-01,  2.73702238e-01, -3.90676334e-01,
       -1.60530826e-01, -1.63805591e+00,  1.91531817e+00, -1.35083786e-01,
        2.71062534e-01, -3.82657803e-02, -2.97553323e-01,  1.77260801e-01,
       -4.81128732e-01,  7.13054023e-01, -1.74997788e+00,  1.37124410e+00,
       -1.48893360e+00,  4.57067488e-01, -1.27437684e+00, -9.18121678e-01,
       -2.29128841e-01, -1.38017032e+00,  8.39225247e-01, -2.58723002e-02,
       -1.32914907e+00, -1.74970919e+00, -7.66259176e-01,  3.19248667e-01,
        5.06566075e-01,  4.63879161e-01, -5.16016592e-01, -7.79097547e-01,
       -1.35937060e+00, -1.96345578e+00,  2.52208200e+00,  1.21588524e+00,
       -5.61026824e-01, -1.22274253e+00, -3.23226818e-01, -1.20434071e+00,
        1.39591614e-01, -4.56156093e-01, -2.28411053e-01,  1.31086807e+00,
        2.23323872e+00, -

In [121]:
alturas_normalizadas.mean()

-7.958078640513122e-16

In [122]:
alturas_normalizadas.std()

1.0