<a href="https://colab.research.google.com/github/GeraldineQuispeT/Programacion101_UTEC/blob/main/01_Introduccion_a_Python/03_Estructuras_de_datos_parte2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >


<h1 align=center><font size = 5>ESTRUCTURAS DE DATOS - PARTE 2
</font></h1>

---


**Tabla de Contenidos**

- Diccionarios
- Sets
- Matrices

---

## 1. Diccionarios

**Concepto:**

Un diccionario es una estructura de datos que almacena pares clave-valor. Las claves deben ser únicas y se utilizan para acceder a los valores asociados.

### Ejemplo 1.1: Creación de Diccionarios y Acceso a Elementos


In [1]:
# Crear un diccionario
persona = {'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}
print(persona)

{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}


In [2]:
# Acceder a un valor
print("Nombre:", persona['nombre'])
print("Ciudad:", persona.get('ciudad'))


Nombre: Ana
Ciudad: Lima


In [3]:

# Añadir un nuevo par clave-valor
persona['profesion'] = 'Ingeniera'
print(persona)

{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima', 'profesion': 'Ingeniera'}


In [4]:
# Eliminar un par clave-valor
del persona['ciudad']
print(persona)

{'nombre': 'Ana', 'edad': 30, 'profesion': 'Ingeniera'}


### Ejemplo 1.2: Métodos Útiles de Diccionarios


In [5]:
# Obtener todas las claves
print(persona.keys())


dict_keys(['nombre', 'edad', 'profesion'])


In [6]:
# Obtener todos los valores
print(persona.values())


dict_values(['Ana', 30, 'Ingeniera'])


In [7]:
# Comprobar si una clave existe en el diccionario
if 'edad' in persona:
    print("La clave 'edad' está en el diccionario.")


La clave 'edad' está en el diccionario.


### Ejercicio 1: Trabajando con Diccionarios

- Crea un diccionario que contenga información sobre un automóvil (marca, modelo, año, color).
- Accede a cada valor usando su clave.
- Añade una clave para el precio del automóvil.
- Elimina la clave del color del automóvil y muestra el diccionario actualizado.
- Usa keys() y values() para imprimir las claves y valores del diccionario.



In [27]:
automovil = {'marca':'Nissan',
             'modelo':'Modelo2024',
             'año':'2024',
             'color':'negro'}

print('Los valores son: ',automovil.keys())
automovil['precio']=250000
print('Los nuevos valores son: ',automovil)
del automovil['color']
print('Los nuevos valores son: ',automovil)

Los valores son:  dict_keys(['marca', 'modelo', 'año', 'color'])
Los nuevos valores son:  {'marca': 'Nissan', 'modelo': 'Modelo2024', 'año': '2024', 'color': 'negro', 'precio': 250000}
Los nuevos valores son:  {'marca': 'Nissan', 'modelo': 'Modelo2024', 'año': '2024', 'precio': 250000}


In [28]:
print('Las claves son: ',automovil.keys())
print('Los valores son: ',automovil.values())

Las claves son:  dict_keys(['marca', 'modelo', 'año', 'precio'])
Los valores son:  dict_values(['Nissan', 'Modelo2024', '2024', 250000])


## 2. Sets

Los sets son colecciones de elementos únicos y desordenados. Son útiles para eliminar duplicados o realizar operaciones matemáticas como intersección y unión.

### Ejemplo 2.1: Creación y Modificación de Sets

In [8]:
# Crear un set
numeros = {1, 2, 3, 4, 5}
print(numeros)


{1, 2, 3, 4, 5}


In [9]:
# Añadir elementos
numeros.add(6)
print(numeros)


{1, 2, 3, 4, 5, 6}


In [10]:
# Eliminar un elemento
numeros.remove(3)
print(numeros)


{1, 2, 4, 5, 6}


### Ejemplo 2.2: Operaciones de Conjuntos


In [11]:
# Crear otro set
otro_set = {4, 5, 6, 7}

In [12]:
# Unión de sets (todos los elementos)
union = numeros.union(otro_set)
print("Unión:", union)


Unión: {1, 2, 4, 5, 6, 7}


In [13]:
# Intersección de sets (elementos comunes)
interseccion = numeros.intersection(otro_set)
print("Intersección:", interseccion)


Intersección: {4, 5, 6}


### Ejercicio 2: Operaciones con Sets

- Crea dos sets de números: uno con números del 1 al 10 y otro con números del 5 al 15.
- Encuentra la intersección y unión de ambos sets.
- Elimina un número del primer set.
- Usa un set para almacenar los nombres de tus amigos. Asegúrate de que no haya duplicados.

In [30]:
set1={1,2,3,4,5,6,7,8,9,10}
set2={5,6,7,8,9,10,11,12,13,14,15}

print('Los valores de la interseccion son: ',set1.intersection(set2))
print('Los valores de la union son: ',set1.union(set2))

Los valores de la interseccion son:  {5, 6, 7, 8, 9, 10}
Los valores de la union son:  {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}


In [33]:
set1.remove(1)
print('Los nuevos numeros del set1 son: ',set1)

Los nuevos numeros del set1 son:  {2, 3, 4, 5, 6, 7, 8, 9, 10}


In [34]:
amigos=set()
amigos.add('Maria')
amigos.add('Juan')
amigos.add('Julia')
amigos.add('Carlos')
amigos.add('Miiran')
amigos.add('Jose')

print('Los nombres de mis amigos son: ', amigos)

Los nombres de mis amigos son:  {'Jose', 'Maria', 'Carlos', 'Miiran', 'Julia', 'Juan'}


## 3. Matrices

En Python, las matrices pueden representarse como listas de listas. Para manipular matrices más avanzadas y realizar cálculos eficientes, utilizamos la librería NumPy.

### Ejemplo 3.1: Matrices con Listas de Listas


In [14]:
# Crear una matriz 3x3 con listas anidadas
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matriz)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [15]:
# Acceder a elementos de la matriz
print("Elemento en [1][1]:", matriz[1][1])


Elemento en [1][1]: 5


In [16]:
# Modificar un elemento
matriz[2][0] = 10
print(matriz)

[[1, 2, 3], [4, 5, 6], [10, 8, 9]]


### Ejemplo 3.2: Manipulación de Matrices con NumPy


In [17]:
import numpy as np

# Crear una matriz 3x3 con NumPy
matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matriz_np)




[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
# Sumar 10 a cada elemento
print(matriz_np + 10)



[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [19]:
# Multiplicar cada elemento por 2
print(matriz_np * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### Ejercicio 3: Operaciones con Matrices

- Crea una matriz 3x3 usando listas de listas.
- Modifica un valor de la matriz y muestra la matriz actualizada.
- Usa NumPy para crear una matriz 4x4 con números aleatorios enteros.
- Realiza una operación de suma con la matriz (suma 5 a cada elemento).
- Multiplica los elementos de la matriz por 2 usando NumPy.

In [38]:
lista1=list(range(1,4))
lista2=list(range(4,7))
lista3=list(range(7,10))

matrix=[lista1,lista2,lista3]
print('La matriz creada es: ',matrix)
matrix[2][0]=10
print('La nueva matriz modificada es: ',matrix)

La matriz creada es:  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
La nueva matriz modificada es:  [[1, 2, 3], [4, 5, 6], [10, 8, 9]]


In [46]:
matrix2 = np.random.randint(0, 10, size=(4, 4))
print('La matriz creada es: ',matrix2)
matrix2 =matrix2+5
print('\nLa matriz +5 es: ',matrix2)
matrix2 =matrix2*2
print('\nLa matriz *2 es: ',matrix2)

La matriz creada es:  [[4 5 1 5]
 [4 6 5 2]
 [7 2 2 3]
 [3 0 8 7]]

La matriz +5 es:  [[ 9 10  6 10]
 [ 9 11 10  7]
 [12  7  7  8]
 [ 8  5 13 12]]

La matriz *2 es:  [[18 20 12 20]
 [18 22 20 14]
 [24 14 14 16]
 [16 10 26 24]]


## 4. Desafío


Eres el encargado de un almacén de productos electrónicos. Tienes un registro de ventas semanales para teléfonos, laptops y tabletas. Necesitas analizar las ventas para mejorar la gestión.

- Crea tres listas: una para teléfonos, otra para laptops y otra para tabletas con las ventas de cada día durante una semana.
- Usa slicing para obtener las ventas de los últimos 3 días de cada producto.
- Usa listas por comprensión para calcular el total de ventas de cada producto y el promedio de ventas diarias.
- Clasifica los productos en "ventas altas" o "ventas bajas" según si el promedio de ventas es mayor o menor a 5.

Instrucciones:
Usa sum() y len() para calcular el total de ventas y el promedio.
Clasifica las ventas usando listas por comprensión.

In [63]:
telefonos = [13, 12, 8, 25, 22, 10, 17]
laptops = [10, 20, 40, 56, 79, 30, 30]
tabletas = [5, 1, 1, 2, 4, 6, 9]

print('Las ventas del producto telefonos para los 3 ultimos dias son: ',telefonos[-3:])
print('Las ventas del producto laptops para los 3 ultimos dias son: ',laptops[-3:])
print('Las ventas del producto tabletas para los 3 ultimos dias son: ',tabletas[-3:])

ventas_telefonos=sum(producto for producto in telefonos)
ventas_laptops=sum(producto for producto in laptops)
ventas_tabletas=sum(producto for producto in tabletas)

promedio_telefonos=int(sum(producto for producto in telefonos)/len(telefonos))
promedio_laptops=int(sum(producto for producto in laptops)/len(laptops))
promedio_tabletas=int(sum(producto for producto in tabletas)/len(tabletas))

print('\nEl total de ventas en telefonos son: ',ventas_telefonos,' y el promedio diario es: ',promedio_telefonos)
print('El total de ventas en laptops son: ',ventas_laptops,' y el promedio diario es: ',promedio_laptops)
print('El total de ventas en tabletas son: ',ventas_tabletas,' y el promedio diario es: ',promedio_tabletas)

def clasifica_productos(promedio_diario):
  if promedio_diario > 5:
    return "buenas ventas"
  else:
    return "malas ventas"

print("\nLa clasificacion del producto telefonos es", clasifica_productos(promedio_telefonos))
print("La clasificacion del producto laptops es", clasifica_productos(promedio_laptops))
print("La clasificacion del producto tabletas es", clasifica_productos(promedio_tabletas))

Las ventas del producto telefonos para los 3 ultimos dias son:  [22, 10, 17]
Las ventas del producto laptops para los 3 ultimos dias son:  [79, 30, 30]
Las ventas del producto tabletas para los 3 ultimos dias son:  [4, 6, 9]

El total de ventas en telefonos son:  107  y el promedio diario es:  15
El total de ventas en laptops son:  265  y el promedio diario es:  37
El total de ventas en tabletas son:  28  y el promedio diario es:  4

La clasificacion del producto telefonos es buenas ventas
La clasificacion del producto laptops es buenas ventas
La clasificacion del producto tabletas es malas ventas


---

# Gracias por completar este laboratorio!

---